apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ping
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 8000
      - path: /ping
        backend:
          serviceName: frontend
          servicePort: 80
