apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - name: grpc
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
