apiVersion: v1
kind: Service
metadata:
  name: service-one
  labels:
    app: service-one
spec:
  ports:
    - name: grpc
      port: 50050
    - name: http
      port: 80
  selector:
    app: service-one
