apiVersion: v1
kind: Service
metadata:
  name: service-two
  labels:
    app: service-two
spec:
  ports:
    - name: grpc
      port: 50050
    - name: http
      port: 80
  selector:
    app: service-two
