apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-v2
spec:
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      containers:
        - name: frontend
          image: gcr.io/hightowerlabs/frontend:v2
          imagePullPolicy: Always
          env:
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster
                  key: region
          args:
            - "-bar=bar:8000"
            - "-foo=foo:8000"
            - "-grpc=0.0.0.0:8000"
            - "-http=0.0.0.0:80"
            - "-region=$(REGION)"
          ports:
            - name: grpc
              containerPort: 8000
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 20M
            requests:
              cpu: 100m
              memory: 10M
