apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    app: frontend
